project:
  type: website

website:
  title: "ISSS608-VAA"
  sidebar:
    style: "docked"
    search: true
    back-to-top-navigation: true
    reader-mode: true
    contents: 
      - section: "Take-home Exercise"
        contents: 
          - Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd
          - Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd
          - Take-home_Ex/Take-home_Ex03/Take-home_Ex03.qmd
          
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

