---
title: "Take Home Exercise 1"
subtitle: Rent
format: 
  html: 
    code-fold: true
    code-summary: "Show the code"
author: "Fangxian"
execute: 
  eval: true
  warning: false
---

# Task

# Getting Started

```{r}
pacman::p_load(tidyverse, ggiraph, plotly, patchwork, DT, gifski, gapminder,gganimate, ggrepel, patchwork, ggthemes, hrbrthemes,FunnelPlotR, knitr, ggstatsplot, crosstalk, ggdist, lubridate, dyplyr)
```

# Data Preparation

```{r}
Participants <- read_csv("data/participants.csv") %>%
  mutate_if(is.character, as.factor)

head(Participants)
```

```{r}
FinancialJournal <- read_csv("data/FinancialJournal.csv") %>%
  mutate_if(is.character, as.factor)

Fin_by_cat <- FinancialJournal %>%
  mutate(date = as.Date(timestamp)) %>%
  group_by(participantId, category, timestamp) %>%
  summarize(amount = sum(amount)) %>%
  pivot_wider(names_from = category, values_from = amount)

head(Fin_by_cat)
```

```{r}
Fin_split_ym <- Fin_by_cat %>%  
    mutate(
    Date = as.Date(timestamp),
    Month_Yr = format(Date, "%Y-%m")) 

head(Fin_split_ym)
```

```{r}
Fin_summ <- Fin_split_ym %>% 
  group_by(participantId, Month_Yr) %>% 
  summarize(
    Education = sum(Education, na.rm = TRUE),
    Food = sum(Food, na.rm = TRUE),
    Recreation = sum(Recreation, na.rm = TRUE),
    Shelter = sum(Shelter, na.rm = TRUE),
    Wage = sum(Wage, na.rm = TRUE),
    RentAdjustment = sum(RentAdjustment, na.rm = TRUE),
    Count = n()
  ) %>% 
  ungroup()%>%
  mutate(
    TotalIncome = Wage + RentAdjustment,
    TotalExpense = Food + Recreation + Shelter + Education,
    TotalSavings = TotalIncome - TotalExpense)
```

```{r}
Fin_final <- Fin_summ %>% 
  group_by(participantId) %>% 
  summarize(
    Education = sum(Education, na.rm = TRUE),
    Food = sum(Food, na.rm = TRUE),
    Recreation = sum(Recreation, na.rm = TRUE),
    Shelter = sum(Shelter, na.rm = TRUE),
    Wage = sum(Wage, na.rm = TRUE),
    RentAdjustment = sum(RentAdjustment, na.rm = TRUE),
    TotalIncome = sum(TotalIncome, na.rm = TRUE),
    TotalExpense = sum(TotalExpense, na.rm = TRUE),
    TotalIncome = sum(TotalIncome, na.rm = TRUE)
  )%>%
  ungroup()

Joined_table <- inner_join(Participants,Fin_final, by = 'participantId')
```

```{r}
ggplot(data=Participants,
       aes(y = joviality,       
           x= educationLevel)) +    
  geom_boxplot()   
```

\
